baseURL = "https://math.iisc.ac.in/~gadgil/algebraic-topology-2024/"
languageCode = "en-us"
title = "MA 332: Algebraic Topology"
theme = "course"
buildFuture = "true"
[params]
    code = "MA 332"
    course = "Algebraic Topology"
    term = "January 2024"
[markup.goldmark.renderer]
unsafe= true